app/__init__.py
from flask import Flask, render_template
# Pretty sure I don't need "render_template" here
from config import Config
from .api.routes import api
from .site.routes import site
from .authentication.routes import auth

from flask_sqlalchemy import SQLAlchemy
# Pretty sure I don't need this. Will have to investigate
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import Blueprint, request, jsonify, render_template, redirect, url_for, flash, session
from helpers import token_required
from models import db, Profile, profile_schema, profile_schemas, UserBooks, book_schema
from forms import UserProfileForm
from flask_login import current_user
import json, urllib.request

api = Blueprint('api',__name__, url_prefix='/api')


# This was an experiment, doesn't need to be done with a try/except
@api.route('/addprofile', methods = ['GET', 'POST'])
def add_profile():
    form = UserProfileForm()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            display_name = form.display_name.data
            profession = form.profession.data
            phone_number = form.phone_number.data
            location = form.location.data
            hobbies = form.hobbies.data
            user_token = current_user.token
            print(phone_number, location)

            profile = Profile(display_name=display_name, profession=profession, phone_number=phone_number, location=location, hobbies=hobbies, user_token=user_token)

            db.session.add(profile)
            db.session.commit()

            
            flash(f'You have successfully added your profile')
            return redirect(url_for('site.profile'))
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('addprofile.html', form=form)

# Get route for profile data display
@api.route('/profile/get/<token>', methods = ['GET'])
def get_profile(token):
    print(token, 'here')
    profile = Profile.query.filter_by(user_token = token).first().__dict__
    print(profile)
    profile_id = profile['id']
    profile_details = Profile.query.filter_by(id = profile_id).first()
    response = profile_schema.dump(profile_details)
    return jsonify(response)
    

# Updating
@api.route('/profile/update', methods = ['GET', 'POST', 'PUT'])
def update_profile():
    form = UserProfileForm()
    try:
        if form.validate_on_submit():
            user_profile = Profile.query.filter_by(user_token = current_user.token).first().__dict__
            profile_id = user_profile['id']
            profile = Profile.query.filter_by(id = profile_id).first()
            profile.display_name = form.display_name.data
            profile.profession = form.profession.data
            profile.phone_number = form.phone_number.data
            profile.location = form.location.data
            profile.hobbies = form.hobbies.data

            db.session.commit()
            

            
            flash(f'You have successfully updated your profile')
            return render_template('profile.html')
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('updateprofile.html', form=form)



# id is book ID user_token will be hard coded
@api.route('/addbook/<id>', methods = ['POST'])
def addbook(id):
    base_url = 'https://www.googleapis.com/books/v1/volumes/'
    target_url = base_url + id

    response = urllib.request.urlopen(target_url)
    data = response.read()
    dict = json.loads(data)
    token = '1e267e224df941eba6bcacc7809a3ee550d021e9b6113cbe'
    title = dict['volumeInfo']['title']
    imgurl = dict['volumeInfo']['imageLinks']['smallThumbnail']
    book = UserBooks(book_id=id, title=title, imgurl=imgurl, user_token=token)

    db.session.add(book)
    db.session.commit()
    return redirect(url_for('site.eapi'))


# DELETE function, HTML forms only allow get and post
@api.route('/deletebook/<id>', methods=['POST'])
def deletebook(id):
    book = UserBooks.query.filter_by(book_id = id).first()
    book_response = UserBooks.query.get(id)
    book_dump = book_schema.dump(book_response)
    db.session.delete(book)
    db.session.commit()
    
    return redirect(url_for('site.eapi'))

    

app/authentication/routes.py
from forms import UserSignupForm, UserLoginForm
from models import User, Profile, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash

# imports for flask login 
from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')


@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserSignupForm()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            first = form.first.data
            last = form.last.data
            email = form.email.data
            password = form.password.data
            print(email, password)

            user = User(first=first, last=last, email=email, password = password)

            db.session.add(user)
            db.session.commit()


            flash(f'You have successfully created a user account {email}', 'User-created')
            return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('sign_up.html', form=form)





@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successful in your initiation. Congratulations, Entrant. Welcome to the Jedi Knights', 'auth-sucess')
                return redirect(url_for('api.add_profile'))
            else:
                flash('You have failed in your attempt to access this content. Must be 99 or older to enter this website', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        print("except")
        raise Exception('Invalid Form Data: Please Check your Form')
    return render_template('sign_in.html', form=form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Flask, request, Blueprint, render_template
import urllib.request, json
import psycopg2
from forms import UserProfileForm
from flask_login import current_user
from models import db, User, Profile, profile_schema, UserBooks


site = Blueprint('site', __name__, template_folder = 'site_templates')

@site.route('/')
def home():
    return render_template('index.html')

# Route for BookShelf page
@site.route('/eapi')
def eapi():
    books = UserBooks.query.all()
    return render_template('externalapi.html', books = books)

# Pull data from local api and third party api to display on profile page

@site.route('/profile')
def profile():
    url = "https://api.quotable.io/random?maxLength=300"

    response = urllib.request.urlopen(url)
    data = response.read()
    dict = json.loads(data)
    quote = dict['content']
    author = dict['author']

    user_token = current_user.token
    print(user_token)

    base_url = 'https://coding-temple-capstone.herokuapp.com/api/profile/get/'
    prof_url = base_url + user_token
    print(prof_url)

    prof_response = urllib.request.urlopen(prof_url)
    prof_data = prof_response.read()
    prof_dict = json.loads(prof_data)
    display_name = prof_dict['display_name']
    profession = prof_dict['profession']
    phone_number = prof_dict['phone_number']
    location = prof_dict['location']
    hobbies = prof_dict['hobbies']

    
    return render_template('profile.html', quote=quote, author=author, display_name=display_name, profession=profession, phone_number=phone_number, location=location, hobbies=hobbies)


# @site.route('/profile/update', methods = ['GET', 'POST'])
# def updateprofile():
#     form = UserProfileForm()
#     return render_template('updateprofile.html', form=form)

app/templates/TEST.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<script src="https://kit.fontawesome.com/126a2de9a0.js" crossorigin="anonymous"></script>
<title>Coffee</title>
</head>
<!-- Navbar Navigation -->

<nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3">
  <div class="container">
      <a href="{{ url_for('site.home') }}" class="navbar-brand">My Website</a>
      <button 
          class="navbar-toggler" 
          type="button" 
          data-bs-toggle="collapse" 
          data-bs-target="#navmenu"
      ><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navmenu">
          <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                  <a href="{{ url_for('site.home') }}" class="nav-link">Home</a>
              </li>
              <li class="nav-item">
                  <a href="{{ url_for('site.profile') }}" class="nav-link">Profile</a>
              </li>
              {% if current_user.is_authenticated %}
              <li class="nav-item">
                  <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                  <a href="{{ url_for('auth.signin') }}" class="nav-link">Sign In</a>
              </li>
              <li class="nav-item">
                  <a href="{{ url_for('auth.signup') }}" class="nav-link">Sign Up</a>
              </li>
              {% endif %}
          </ul>
      </div>
  </div>
</nav>

<!-- Navbar Navigation -->
<body class="">
   <!-- !Content will extend here -->

   <div class="row py-5 px-4" style="background-color: #303C40;"> 
    <div class="col-md-5 mx-auto"> 
        <!-- Profile widget --> 
        <div class="bg-dark shadow rounded overflow-hidden"> 
            <div class="px-4 pt-0 pb-4 cover"> 
                <div class="media align-items-end profile-head"> 
                    <div class="profile mr-3">
                        <img src="../../static/images/profile_pic.jpg" alt="Profile Picture" width="130" class="rounded mb-2 img-thumbnail">
                        <a href="#" class="btn btn-outline-dark btn-sm btn-block">Edit profile</a>
                    </div> 
                    <div class="media-body mb-5 text-white"> 
                        <h4 class="mt-0 mb-0">Mark Williams</h4> 
                        <p class="small mb-4"> 
                        <i class="fas fa-map-marker-alt mr-2"></i>New York</p> 
                    </div> 
                    </div> 
                </div> 
                <div class="bg-light p-4 d-flex justify-content-end text-center"> 
                    <ul class="list-inline mb-0"> 
                        <li class="list-inline-item"> 
                            <h5 class="font-weight-bold mb-0 d-block">215</h5>
                            <small class="text-muted"> 
                                <i class="fas fa-image mr-1"></i>Photos</small> 
                        </li> 
                            <li class="list-inline-item"> <h5 class="font-weight-bold mb-0 d-block">745</h5>
                                <small class="text-muted"> 
                                <i class="fas fa-user mr-1"></i>Followers</small> 
                            </li> 
                            <li class="list-inline-item"> 
                                <h5 class="font-weight-bold mb-0 d-block">340</h5>
                                <small class="text-muted"> <i class="fas fa-user mr-1"></i>Following</small>
                            </li> 
                        </ul> 
                    </div> 
                    <div class="px-4 py-3"> 
                        <h5 class="mb-0">About</h5> 
                        <div class="p-4 rounded shadow-sm bg-light"> 
                            <p class="font-italic mb-0">Web Developer</p> 
                            <p class="font-italic mb-0">Lives in New York</p> 
                            <p class="font-italic mb-0">Photographer</p> 
                        </div> 
                    </div> 
                    <div class="py-4 px-4"> 
                        <div class="d-flex align-items-center justify-content-between mb-3"> 
                            <h5 class="mb-0 text-muted">Recent photos</h5>
                            <a href="#" class="btn btn-link text-muted">Show all</a> 
                        </div> 
                        <div class="row"> 
                            <div class="col-lg-6 mb-2 pr-lg-1">
                                <img src="https://images.unsplash.com/photo-1469594292607-7bd90f8d3ba4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="" class="img-fluid rounded shadow-sm">
                            </div> 
                                <div class="col-lg-6 mb-2 pl-lg-1">
                                    <img src="https://images.unsplash.com/photo-1493571716545-b559a19edd14?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="" class="img-fluid rounded shadow-sm">
                                </div> 
                                    <div class="col-lg-6 pr-lg-1 mb-2">
                                        <img src="https://images.unsplash.com/photo-1453791052107-5c843da62d97?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="" class="img-fluid rounded shadow-sm">
                                    </div> 
                                        <div class="col-lg-6 pl-lg-1">
                                            <img src="https://images.unsplash.com/photo-1475724017904-b712052c192a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="" class="img-fluid rounded shadow-sm">
                                        </div>
                                    </div> 
                                </div> 
                            </div> 
                        </div>
</div>

   <!-- !Content will extend here -->
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
<!-- Footer -->
<footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="opacity-50 btn btn-outline-light btn-floating m-1" href="#!" role="button">
        <i class="fab fa-facebook-f"></i>
      </a>

      <!-- Twitter -->
      <a class="opacity-50 btn btn-outline-light btn-floating m-1" href="#!" role="button">
        <i class="fab fa-twitter"></i>
      </a>

      <!-- Instagram -->
      <a class="opacity-50 btn btn-outline-light btn-floating m-1" href="#!" role="button">
        <i class="fab fa-instagram"></i>
      </a>

      <!-- Linkedin -->
      <a class="opacity-50 btn btn-outline-light btn-floating m-1" href="#!" role="button">
        <i class="fab fa-linkedin-in"></i>
      </a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="https://github.com/TrashBandiHoot" role="button">
        <i class="fab fa-github"></i>
      </a>
    </section>
    <!-- Section: Social media -->

    <!-- Section: Text -->
    <section class="mb-4">
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt distinctio earum
        repellat quaerat voluptatibus placeat nam, commodi optio pariatur est quia magnam
        eum harum corrupti dicta, aliquam sequi voluptate quas.
      </p>
    </section>
    <!-- Section: Text -->

    <!-- Section: Links -->
    <section class="container-fluid">
      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-lg-6 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-white">Link 1</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 2</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 3</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-6 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-white">Link 1</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 2</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 3</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-white" href="https://github.com/TrashBandiHoot">Dominic Davenport</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
</html>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
<script src="https://kit.fontawesome.com/126a2de9a0.js" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="{{url_for('static', filename='main.js')}}"></script>
<title>CapStone</title>
</head>
<!-- Navbar Navigation -->

<nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3">
  <div class="container">
      <a href="{{ url_for('site.home') }}" class="navbar-brand">My Website</a>
      <button 
          class="navbar-toggler" 
          type="button" 
          data-bs-toggle="collapse" 
          data-bs-target="#navmenu"
      ><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navmenu">
          <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                  <a href="{{ url_for('site.home') }}" class="nav-link">Home</a>
              </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a href="{{ url_for('site.profile') }}" class="nav-link">Profile</a>
            </li>
            <li class="nav-item">
            <a href="{{ url_for('site.eapi') }}" class="nav-link">BookShelf</a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a href="{{ url_for('auth.signin') }}" class="nav-link">Sign In</a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('auth.signup') }}" class="nav-link">Sign Up</a>
            </li>
            {% endif %}
          </ul>
      </div>
  </div>
</nav>

<!-- Navbar Navigation -->
<body class="">
   <!-- !Content will extend here -->

{% block content %}
{% endblock %}

   <!-- !Content will extend here -->
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
<!-- Footer -->
<footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="opacity-50 btn btn-outline-light btn-floating m-1" href="#!" role="button">
        <i class="fab fa-facebook-f"></i>
      </a>

      <!-- Twitter -->
      <a class="opacity-50 btn btn-outline-light btn-floating m-1" href="#!" role="button">
        <i class="fab fa-twitter"></i>
      </a>

      <!-- Instagram -->
      <a class="opacity-50 btn btn-outline-light btn-floating m-1" href="#!" role="button">
        <i class="fab fa-instagram"></i>
      </a>

      <!-- Linkedin -->
      <a class="opacity-50 btn btn-outline-light btn-floating m-1" href="#!" role="button">
        <i class="fab fa-linkedin-in"></i>
      </a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="https://github.com/TrashBandiHoot" role="button">
        <i class="fab fa-github"></i>
      </a>
    </section>
    <!-- Section: Social media -->

    <!-- Section: Text -->
    <section class="mb-4">
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt distinctio earum
        repellat quaerat voluptatibus placeat nam, commodi optio pariatur est quia magnam
        eum harum corrupti dicta, aliquam sequi voluptate quas.
      </p>
    </section>
    <!-- Section: Text -->

    <!-- Section: Links -->
    <section class="container-fluid">
      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-lg-6 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-white">Link 1</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 2</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 3</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-6 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-white">Link 1</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 2</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 3</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-white" href="https://github.com/TrashBandiHoot">Dominic Davenport</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
</html>

app/templates/forms.html
              
              <form method="POST">
                {{ form.hidden_tag() }}
                <div class="form-outline mb-2">
                    <fieldset id="first-field">
                        {{ form.first.label }}
                        {{ form.first(class = 'form-control', placeholder = 'First Name ') }}
                    </fieldset>
                </div>

                <div class="form-outline mb-2">
                    <fieldset id="last-field">
                        {{ form.last.label }}
                        {{ form.last(class = 'form-control', placeholder = 'Last Name ') }}
                    </fieldset>
                </div>

                <div class="form-outline mb-2">
                    <fieldset id="email-field">
                        {{ form.email.label }}
                        {{ form.email(class = 'form-control', placeholder = 'Email ') }}
                    </fieldset>
                </div>

                <div class="form-outline mb-2">
                    <fieldset id="pass-field">
                        {{ form.password.label }}
                        {{ form.password(class = "form-control", placeholder = "Password ") }}
                    </fieldset>
                </div>

                <div class="d-flex justify-content-center">
                    {{ form.submit_button(class = "btn btn-primary btn-block mt-2") }}
                </div>

                <p class="text-center text-muted mt-5 mb-0">Have already an account? <a href="{{ url_for('auth.signin') }}"
                    class="fw-bold text-body"><u>Login here</u></a></p>

              </form>

app/templates/logform.html
              
              <form method="POST">
                {{ form.hidden_tag() }}
                <div class="form-outline mb-2">
                    <fieldset id="email-field">
                        {{ form.email.label }}
                        {{ form.email(class = 'form-control', placeholder = 'Email ') }}
                    </fieldset>
                </div>

                <div class="form-outline mb-2">
                    <fieldset id="pass-field">
                        {{ form.password.label }}
                        {{ form.password(class = "form-control", placeholder = "Password ") }}
                    </fieldset>
                </div>

                <div class="d-flex justify-content-center">
                    {{ form.submit_button(class = "btn btn-primary btn-block mt-2") }}
                </div>

              </form>

app/templates/profileform.html
              
              <form method="POST">
                {{ form.hidden_tag() }}
                <div class="form-outline mb-2">
                    <fieldset id="name-field">
                        {{ form.display_name.label }}
                        {{ form.display_name(class = 'form-control', placeholder = 'Display Name ') }}
                    </fieldset>
                </div>

                <div class="form-outline mb-2">
                    <fieldset id="profession-field">
                        {{ form.profession.label }}
                        {{ form.profession(class = 'form-control', placeholder = 'Profession ') }}
                    </fieldset>
                </div>

                <div class="form-outline mb-2">
                    <fieldset id="phone_number-field">
                        {{ form.phone_number.label }}
                        {{ form.phone_number(class = 'form-control', placeholder = 'Phone Number ') }}
                    </fieldset>
                </div>

                <div class="form-outline mb-2">
                    <fieldset id="location-field">
                        {{ form.location.label }}
                        {{ form.location(class = "form-control", placeholder = "Location ") }}
                    </fieldset>
                </div>

                <div class="form-outline mb-2">
                    <fieldset id="hobbies-field">
                        {{ form.hobbies.label }}
                        {{ form.hobbies(class = "form-control", placeholder = "Hobbies ") }}
                    </fieldset>
                </div>

                <div class="d-flex justify-content-center">
                    {{ form.submit_button(class = "btn btn-primary btn-block mt-2") }}
                </div>

              </form>

app/templates/profileupdateform.html
              
             
              <form method="POST">
                {{ form.hidden_tag() }}
                <div class="form-outline mb-2">
                    <fieldset id="name-field">
                        {{ form.display_name.label }}
                        {{ form.display_name(class = 'form-control', placeholder = 'Display Name ') }}
                    </fieldset>
                </div>

                <div class="form-outline mb-2">
                    <fieldset id="profession-field">
                        {{ form.profession.label }}
                        {{ form.profession(class = 'form-control', placeholder = 'Profession ') }}
                    </fieldset>
                </div>

                <div class="form-outline mb-2">
                    <fieldset id="phone_number-field">
                        {{ form.phone_number.label }}
                        {{ form.phone_number(class = 'form-control', placeholder = 'Phone Number ') }}
                    </fieldset>
                </div>

                <div class="form-outline mb-2">
                    <fieldset id="location-field">
                        {{ form.location.label }}
                        {{ form.location(class = "form-control", placeholder = "Location ") }}
                    </fieldset>
                </div>

                <div class="form-outline mb-2">
                    <fieldset id="hobbies-field">
                        {{ form.hobbies.label }}
                        {{ form.hobbies(class = "form-control", placeholder = "Hobbies ") }}
                    </fieldset>
                </div>

                <div class="d-flex justify-content-center">
                    {{ form.submit_button(class = "btn btn-primary btn-block mt-2") }}
                </div>

              </form>

app/templates/quotes.html
<q>{{ quote }}</q><br>
<b>{{ author }}</b>

app/templates/updateprofile.html
{% extends 'base.html' %}

{% block content %}

<section class="bg-image" style='min-height: 80vh; background-color: #303C40;''>

<div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-75">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Add information for your Profile</h2>

              {% include 'profileupdateform.html' %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}